# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-07 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emprego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=250)),
                ('empresa', models.CharField(max_length=100)),
                ('area_atuacao', models.CharField(max_length=100)),
                ('local_trabalho', models.CharField(max_length=100)),
                ('quantidade_vagas', models.PositiveIntegerField()),
                ('jornada_trabalho', models.PositiveIntegerField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('atribuicoes', models.TextField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
