# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='cpf_cnpj',
            new_name='cpf',
        ),
    ]
