# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-22 22:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropostaProjeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oferta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tempo', models.PositiveIntegerField()),
                ('infos', models.CharField(max_length=500)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Projeto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='projeto',
            name='propostas',
            field=models.ManyToManyField(related_name='propostas', through='core.PropostaProjeto', to=settings.AUTH_USER_MODEL),
        ),
    ]
