# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-15 03:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=250)),
                ('empresa', models.CharField(max_length=100)),
                ('area_atuacao', models.CharField(max_length=100)),
                ('local_trabalho', models.CharField(max_length=100)),
                ('quantidade_vagas', models.PositiveIntegerField()),
                ('jornada_trabalho', models.PositiveIntegerField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('atribuicoes', models.TextField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=250)),
                ('cpf', models.CharField(blank=True, max_length=45, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=45, null=True)),
                ('genero', models.CharField(blank=True, choices=[('m', 'Masculino'), ('f', 'Feminino')], max_length=1, null=True)),
                ('perfil', models.CharField(choices=[('e', 'Empresa'), ('t', 'Trabalhador')], max_length=1)),
                ('telefone', models.CharField(blank=True, max_length=45, null=True)),
                ('endereco', models.CharField(max_length=120)),
                ('data_nacimento', models.DateField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
